---
name: Build and Publish

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-publish:
    name: Publish container image
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_REGISTRY_USER }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: BUILDER_SRC=github.com/osbuild/fedora-bot
          push: true
          file: Dockerfile
          tags: quay.io/osbuild/fedora-bot:latest